# Form implementation generated from reading ui file 'create_driver.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class CreateDriverWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(793, 138)
        self.label_license_numer = QtWidgets.QLabel(parent=self)
        self.label_license_numer.setGeometry(QtCore.QRect(10, 87, 141, 16))
        self.label_license_numer.setObjectName("label_license_numer")
        self.lineEdit_license_number = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_license_number.setGeometry(
            QtCore.QRect(150, 85, 241, 21))
        self.lineEdit_license_number.setObjectName("lineEdit_license_number")
        self.label_fio_full = QtWidgets.QLabel(parent=self)
        self.label_fio_full.setGeometry(QtCore.QRect(10, 27, 111, 16))
        self.label_fio_full.setObjectName("label_fio_full")
        self.label_license_category = QtWidgets.QLabel(parent=self)
        self.label_license_category.setGeometry(QtCore.QRect(400, 87, 111, 16))
        self.label_license_category.setObjectName("label_license_category")
        self.label_fio_short_data = QtWidgets.QLabel(parent=self)
        self.label_fio_short_data.setGeometry(QtCore.QRect(440, 27, 181, 20))
        self.label_fio_short_data.setText("")
        self.label_fio_short_data.setObjectName("label_fio_short_data")
        self.lineEdit_license_cat = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_license_cat.setGeometry(QtCore.QRect(510, 85, 41, 21))
        self.lineEdit_license_cat.setObjectName("lineEdit_license_cat")

        self.lineEdit_fio_full = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_fio_full.setGeometry(QtCore.QRect(120, 25, 231, 21))
        self.lineEdit_fio_full.setObjectName("lineEdit_fio_full")
        self.lineEdit_fio_full.textChanged.connect(self.change_fio)

        self.label_prefix_data = QtWidgets.QLabel(parent=self)
        self.label_prefix_data.setGeometry(QtCore.QRect(700, 27, 60, 16))
        self.label_prefix_data.setText("")
        self.label_prefix_data.setObjectName("label_prefix_data")
        self.label_fio_short = QtWidgets.QLabel(parent=self)
        self.label_fio_short.setGeometry(QtCore.QRect(360, 27, 71, 16))
        self.label_fio_short.setObjectName("label_fio_short")
        self.label_prefix = QtWidgets.QLabel(parent=self)
        self.label_prefix.setGeometry(QtCore.QRect(630, 27, 60, 16))
        self.label_prefix.setObjectName("label_prefix")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self)
        self.buttonBox.setGeometry(QtCore.QRect(590, 80, 164, 32))
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def change_fio(self):
        fio_arr = self.lineEdit_fio_full.text().split(' ')
        if isinstance(fio_arr, list):
            if len(fio_arr) == 2 and len(fio_arr[1]) > 0:
                fio_short = f"{fio_arr[0]} {fio_arr[1][0]}."
                prefix = f"{fio_arr[0][0]}{fio_arr[1][0]}"
            elif len(fio_arr) == 3 and len(fio_arr[2]) > 0:
                fio_short = f"{fio_arr[0]} {fio_arr[1][0]}.{fio_arr[2][0]}."
                prefix = f"{fio_arr[0][0]}{fio_arr[1][0]}{fio_arr[2][0]}"
            else:
                if len(fio_arr[0]) > 0:
                    fio_short = f"{fio_arr[0]}"
                    prefix = f"{fio_arr[0][0]}"
                else:
                    fio_short = ''
                    prefix = ''
            self.label_fio_short_data.setText(fio_short)
            self.label_prefix_data.setText(prefix)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Создание водителя"))
        self.label_license_numer.setText(
            _translate("Form", "Серия и номер прав:"))
        self.label_fio_full.setText(_translate("Form", "ФИО полностью:"))
        self.label_license_category.setText(
            _translate("Form", "Категория прав:"))
        self.label_fio_short.setText(_translate("Form", "ФИО сокр:"))
        self.label_prefix.setText(_translate("Form", "Префикс:"))

