# Form implementation generated from reading ui file 'create_car.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class CreateCarWindow(QtWidgets.QWidget):
    # def setupUi(self, create_driver_form):
    def __init__(self, fuel_data: dict):
        super().__init__()
        self.fuel_data = fuel_data
        self.setObjectName("create_driver_form")
        self.resize(400, 300)
        self.setMinimumSize(QtCore.QSize(400, 300))
        self.setMaximumSize(QtCore.QSize(400, 300))
        self.label_model = QtWidgets.QLabel(parent=self)
        self.label_model.setGeometry(QtCore.QRect(30, 32, 111, 16))
        self.label_model.setObjectName("label_model")
        self.label_gov_number = QtWidgets.QLabel(parent=self)
        self.label_gov_number.setGeometry(QtCore.QRect(30, 72, 81, 16))
        self.label_gov_number.setObjectName("label_gov_number")
        self.label_fuel_type = QtWidgets.QLabel(parent=self)
        self.label_fuel_type.setGeometry(QtCore.QRect(30, 142, 81, 16))
        self.label_fuel_type.setObjectName("label_fuel_type")
        self.comboBox_fuel_type = QtWidgets.QComboBox(parent=self)
        self.comboBox_fuel_type.setGeometry(QtCore.QRect(120, 140, 104, 26))
        self.comboBox_fuel_type.setObjectName("comboBox_fuel_type")
        for fuel in self.fuel_data:
            self.comboBox_fuel_type.addItem(fuel, self.fuel_data[fuel])
        self.comboBox_fuel_type.setCurrentIndex(-1)
        self.comboBox_fuel_type.currentTextChanged.connect(self.change_fuel_code)

        self.label_max_fuel_rate = QtWidgets.QLabel(parent=self)
        self.label_max_fuel_rate.setGeometry(QtCore.QRect(30, 182, 211, 16))
        self.label_max_fuel_rate.setObjectName("label_max_fuel_rate")
        self.label_max_fuel_code = QtWidgets.QLabel(parent=self)
        self.label_max_fuel_code.setGeometry(QtCore.QRect(30, 220, 91, 16))
        self.label_max_fuel_code.setObjectName("label_max_fuel_code")
        self.label_max_fuel_code_value = QtWidgets.QLabel(parent=self)
        self.label_max_fuel_code_value.setGeometry(QtCore.QRect(120, 220, 171, 16))
        self.label_max_fuel_code_value.setText("")
        self.label_max_fuel_code_value.setObjectName("label_max_fuel_code_value")
        self.lineEdit_max_fuel_rate = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_max_fuel_rate.setGeometry(QtCore.QRect(240, 180, 51, 21))
        self.lineEdit_max_fuel_rate.setObjectName("lineEdit_max_fuel_rate")
        self.lineEdit_model = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_model.setGeometry(QtCore.QRect(150, 30, 221, 21))
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.lineEdit_gov_number = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_gov_number.setGeometry(QtCore.QRect(120, 70, 141, 21))
        self.lineEdit_gov_number.setObjectName("lineEdit_gov_number")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self)
        self.buttonBox.setGeometry(QtCore.QRect(220, 250, 164, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def change_fuel_code(self):
        self.label_max_fuel_code_value.setText(self.fuel_data[self.comboBox_fuel_type.currentText()])

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("create_driver_form", "Создание автомобиля"))
        self.label_model.setText(_translate("create_driver_form", "Марка и модель:"))
        self.label_gov_number.setText(_translate("create_driver_form", "Гос. номер:"))
        self.label_fuel_type.setText(_translate("create_driver_form", "Тип топлива:"))
        self.label_max_fuel_rate.setText(_translate("create_driver_form", "Максимальный расход топлива:"))
        self.label_max_fuel_code.setText(_translate("create_driver_form", "Код топлива:"))

